services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: chust
      POSTGRES_PASSWORD: chust_dev_parol
      POSTGRES_DB: chustapp
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chust -d chustapp"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  dbdata:
