ALTER TABLE products ADD COLUMN IF NOT EXISTS category   TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS image_url  TEXT NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock      INT  NOT NULL DEFAULT 0;
