ALTER TABLE users
    ADD COLUMN IF NOT EXISTS address_lat       DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS address_lng       DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS address_text      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS address_entrance  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS address_floor     TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS address_apartment TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS address_intercom  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS address_comment   TEXT NOT NULL DEFAULT '';
